#############################################################################
# Makefile for building: TrabShaders
# Generated by qmake (2.01a) (Qt 4.8.0) on: Tue Apr 24 09:58:04 2012
# Project:  TrabShaders.pro
# Template: app
# Command: /opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake -spec /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -o Makefile TrabShaders.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -I. -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtCore -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtGui -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtOpenGL -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/include -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/QtSDK/Desktop/Qt/4.8.0/gcc/lib
LIBS          = $(SUBLIBS)  -L/opt/QtSDK/Desktop/Qt/4.8.0/gcc/lib -L/usr/X11R6/lib -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		glwidget.cpp \
		light.cpp \
		material.cpp \
		camera.cpp \
		help.cpp \
		PCBCGSolver.cxx \
		IDSet.cxx \
		PointTool.cxx moc_mainwindow.cpp \
		moc_glwidget.cpp \
		moc_help.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		glwidget.o \
		light.o \
		material.o \
		camera.o \
		help.o \
		PCBCGSolver.o \
		IDSet.o \
		PointTool.o \
		moc_mainwindow.o \
		moc_glwidget.o \
		moc_help.o \
		qrc_resources.o
DIST          = /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/opengl.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		TrabShaders.pro
QMAKE_TARGET  = TrabShaders
DESTDIR       = 
TARGET        = TrabShaders

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_help.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TrabShaders.pro  /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++/qmake.conf /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/opengl.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -o Makefile TrabShaders.pro
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/opengl.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -o Makefile TrabShaders.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TrabShaders1.0.0 || $(MKDIR) .tmp/TrabShaders1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TrabShaders1.0.0/ && $(COPY_FILE) --parents mainwindow.h glwidget.h light.h material.h camera.h help.h trackball.h IDList.h Polyhedron.h PCBCGSolver.h PointTool.h IDSet.h PolarList.h Point3d.h Point2d.h .tmp/TrabShaders1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/TrabShaders1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp glwidget.cpp light.cpp material.cpp camera.cpp help.cpp PCBCGSolver.cxx IDSet.cxx PointTool.cxx .tmp/TrabShaders1.0.0/ && $(COPY_FILE) --parents mainwindow.ui help.ui .tmp/TrabShaders1.0.0/ && (cd `dirname .tmp/TrabShaders1.0.0` && $(TAR) TrabShaders1.0.0.tar TrabShaders1.0.0 && $(COMPRESS) TrabShaders1.0.0.tar) && $(MOVE) `dirname .tmp/TrabShaders1.0.0`/TrabShaders1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TrabShaders1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_glwidget.cpp moc_help.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_glwidget.cpp moc_help.cpp
moc_mainwindow.cpp: help.h \
		mainwindow.h
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_glwidget.cpp: trackball.h \
		camera.h \
		light.h \
		material.h \
		glwidget.h
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) glwidget.h -o moc_glwidget.cpp

moc_help.cpp: help.h
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) help.h -o moc_help.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		pedregulho.jpg \
		pedra2.bmp \
		xadrez.png \
		BTStone.bmp \
		limao.jpg \
		ufabc.jpg \
		fogo.jpg \
		laranja.jpg \
		agua.jpg \
		pedra.jpg \
		sphere.off \
		posy.jpg \
		posz.jpg \
		negx.jpg \
		negy.jpg \
		negz.jpg \
		posx.jpg \
		fieldstone-n.jpg \
		fieldstone-c.jpg \
		fshader5.glsl \
		vshader11.glsl \
		vshader4.glsl \
		vshader7.glsl \
		fshader2.glsl \
		fshader12.glsl \
		vshader10.glsl \
		vshader1.glsl \
		vshader9.glsl \
		fshader4.glsl \
		fshader7.glsl \
		fshader11.glsl \
		vshader6.glsl \
		fshader1.glsl \
		fshader10.glsl \
		vshader3.glsl \
		fshader9.glsl \
		vshader8.glsl \
		fshader6.glsl \
		vshader5.glsl \
		fshader3.glsl \
		vshader12.glsl \
		vshader2.glsl \
		fshader8.glsl
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_help.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_help.h
ui_mainwindow.h: mainwindow.ui \
		glwidget.h \
		trackball.h \
		camera.h \
		light.h \
		material.h
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_help.h: help.ui
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic help.ui -o ui_help.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		help.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		help.h \
		ui_mainwindow.h \
		glwidget.h \
		trackball.h \
		camera.h \
		light.h \
		material.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

glwidget.o: glwidget.cpp glwidget.h \
		trackball.h \
		camera.h \
		light.h \
		material.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o glwidget.cpp

light.o: light.cpp light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o light.o light.cpp

material.o: material.cpp material.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o material.o material.cpp

camera.o: camera.cpp camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

help.o: help.cpp help.h \
		ui_help.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o help.o help.cpp

PCBCGSolver.o: PCBCGSolver.cxx PCBCGSolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PCBCGSolver.o PCBCGSolver.cxx

IDSet.o: IDSet.cxx IDList.h \
		PolarList.h \
		IDSet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IDSet.o IDSet.cxx

PointTool.o: PointTool.cxx Point3d.h \
		Point2d.h \
		PointTool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PointTool.o PointTool.cxx

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_help.o: moc_help.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_help.o moc_help.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

